#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0
FAIL=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

assert() {
  local desc="$1"
  local condition="$2"
  TOTAL=$((TOTAL + 1))
  if eval "$condition"; then
    echo -e "  ${GREEN}PASS${NC} $desc"
    PASS=$((PASS + 1))
  else
    echo -e "  ${RED}FAIL${NC} $desc"
    FAIL=$((FAIL + 1))
  fi
}

echo "ADLC Contract Checks"
echo "Root: $ROOT"
echo ""

echo "--- JSON ---"
assert "applicability-manifest schema parses" "jq empty '$ROOT/docs/schemas/applicability-manifest.schema.json' >/dev/null 2>&1"
assert "build-brief schema parses" "jq empty '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null 2>&1"
assert "skills manifest parses" "jq empty '$ROOT/skills/manifest.json' >/dev/null 2>&1"
assert "applicability issue set parses" "jq empty '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null 2>&1"

echo ""
echo "--- Build Brief Contract ---"
assert "build brief requires applicability_manifest" "jq -e '.required | index(\"applicability_manifest\")' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "task schema requires task_classification" "jq -e '.definitions.task.required | index(\"task_classification\")' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "task schema requires verification_spec" "jq -e '.definitions.task.required | index(\"verification_spec\")' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "task schema keeps failure_modes required" "jq -e '.definitions.task.required | index(\"failure_modes\")' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "change surface includes service_boundary_change" "jq -e '.properties.change_surface.required | index(\"service_boundary_change\")' '$ROOT/docs/schemas/applicability-manifest.schema.json' >/dev/null"

echo ""
echo "--- Prompt Contracts ---"
assert "triage emits task classification" "rg -q 'task_classification' '$ROOT/agents/triage.md'"
assert "planner references applicability manifest" "rg -q 'applicability_manifest' '$ROOT/agents/planner.md'"
assert "coder uses verification_spec" "rg -q 'verification_spec' '$ROOT/agents/coder.md'"
assert "verification discipline is task-class-aware" "rg -q 'build_validation|lint_cleanup' '$ROOT/skills/tdd-enforcement/SKILL.md'"
assert "codegen context consumes verification_spec" "rg -q 'verification_spec' '$ROOT/skills/codegen-context/SKILL.md'"
assert "DoD uses core baseline and overlays" "rg -q 'core baseline|overlay' '$ROOT/skills/definition-of-done/SKILL.md'"
assert "eval council checks applicability manifest" "rg -q 'applicability_manifest' '$ROOT/skills/eval-council/SKILL.md'"
assert "fix loop uses primary verifier wording" "rg -q 'primary verifier' '$ROOT/skills/fix-loop/SKILL.md'"
assert "JIRA ticket creation preserves verification contract" "rg -q 'Verification Contract|task_classification|verification_spec' '$ROOT/skills/jira-ticket-creation/SKILL.md'"
assert "Confluence decomposition respects applicability manifest" "rg -q 'applicability_manifest|active Build Brief sections' '$ROOT/skills/confluence-decomposition/SKILL.md'"

echo ""
echo "--- Activation Metadata ---"
assert "security-review has activation metadata" "jq -e '.skills[] | select(.name==\"security-review\") | .activation.consumes_manifest == true' '$ROOT/skills/manifest.json' >/dev/null"
assert "observability-contract has activation metadata" "jq -e '.skills[] | select(.name==\"observability-contract\") | .activation.mode == \"overlay\"' '$ROOT/skills/manifest.json' >/dev/null"
assert "definition-of-done declares core checks" "jq -e '.skills[] | select(.name==\"definition-of-done\") | (.activation.core_checks | length) > 0' '$ROOT/skills/manifest.json' >/dev/null"
assert "build-feature consumes manifest" "jq -e '.skills[] | select(.name==\"build-feature\") | .activation.consumes_manifest == true' '$ROOT/skills/manifest.json' >/dev/null"

echo ""
echo "--- gen_tests Authoring ---"
assert "spec-to-tests skill file exists" "[ -f '$ROOT/skills/spec-to-tests/SKILL.md' ]"
assert "test-author agent file exists" "[ -f '$ROOT/agents/test-author.md' ]"
assert "spec-to-tests consumes manifest" "jq -e '.skills[] | select(.name==\"spec-to-tests\") | .activation.consumes_manifest == true' '$ROOT/skills/manifest.json' >/dev/null"
assert "test-author agent maps to gen_tests" "jq -e '.agents[] | select(.name==\"test-author\") | .dag_node == \"gen_tests\"' '$ROOT/skills/manifest.json' >/dev/null"
assert "test-author agent declares done stuck revise labels" "jq -e '.agents[] | select(.name==\"test-author\") | (.labels | index(\"done\")) != null and (.labels | index(\"stuck\")) != null and (.labels | index(\"revise\")) != null' '$ROOT/skills/manifest.json' >/dev/null"
assert "WORKFLOW.dot promotes gen_tests to agent styling" "rg -q 'gen_tests \\[shape=box, label=\"Generate Verifiers\\\\nAuthor Failing Tests / Reproducers\", style=filled, fillcolor=\"#e6f3ff\"\\]' '$ROOT/WORKFLOW.dot'"
assert "WORKFLOW.dot no longer marks gen_tests as dashed" "! rg -q 'gen_tests .*dashed' '$ROOT/WORKFLOW.dot'"
assert "WORKFLOW.md table includes test-author row" "rg -q 'agents/test-author\\.md.*spec-to-tests, tdd-enforcement, qa-test-data' '$ROOT/WORKFLOW.md'"
assert "WORKFLOW.md removes gen_tests tool block" "! rg -q '^gen_tests:' '$ROOT/WORKFLOW.md'"
assert "coder consumes test_plan.json" "rg -q 'test_plan\\.json|test_plan_missing|generated_tests' '$ROOT/agents/coder.md'"
assert "README lists spec-to-tests in core engineering" "rg -q 'spec-to-tests.*failing-test authoring from Brief' '$ROOT/README.md'"
assert "README lists test-author agent" "rg -q '\\| \\*\\*test-author\\*\\* \\| Authors failing verifier tests from Brief \\| Sonnet \\| spec-to-tests, tdd-enforcement, qa-test-data \\|' '$ROOT/README.md'"
assert "applicability-manifest verifier includes target_files and expected_failure_mode" "jq -e '.definitions.verifier.properties.target_files.type == \"array\" and .definitions.verifier.properties.expected_failure_mode.type == \"string\"' '$ROOT/docs/schemas/applicability-manifest.schema.json' >/dev/null"
assert "build-brief verifier mirrors target_files and expected_failure_mode" "jq -e '.definitions.verifier.properties.target_files.type == \"array\" and .definitions.verifier.properties.expected_failure_mode.type == \"string\"' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "build-brief keeps string acceptance criteria for backward compatibility" "jq -e '.definitions.task.properties.acceptance_criteria.items.oneOf[] | select(.type==\"string\") | .minLength == 1' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "build-brief accepts structured acceptance criteria objects" "jq -e '.definitions.task.properties.acceptance_criteria.items.oneOf[] | select(.type==\"object\") | .properties.id.pattern == \"^AC-[A-Z0-9_-]+$\"' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "applicability manifest spec documents optional verifier fields" "rg -q 'Optional Fields|target_files|expected_failure_mode' '$ROOT/docs/specs/applicability-manifest.md'"
assert "spec-to-tests skill declares all six quality gates" "rg -q 'acceptance_criteria.*>=1 generated test' '$ROOT/skills/spec-to-tests/SKILL.md' && rg -q 'Every test has at least one concrete assertion' '$ROOT/skills/spec-to-tests/SKILL.md' && rg -q 'Pre-change run captured; failure reason matches .*expected_failure_mode' '$ROOT/skills/spec-to-tests/SKILL.md' && rg -q 'Test file paths intersect .*verification_spec\\.target_files' '$ROOT/skills/spec-to-tests/SKILL.md' && rg -q 'Generated tests pass stop-slop anti-stub patterns' '$ROOT/skills/spec-to-tests/SKILL.md' && rg -q 'test_plan\\.json.*validates against the schema in this skill' '$ROOT/skills/spec-to-tests/SKILL.md'"

echo ""
echo "--- Post-Fix-0 Hardening ---"
assert "codegen-context declares AC normalization" "rg -q 'Normalize Acceptance Criteria|objective-derived|AC-\\{task_id\\}-\\{n\\}' '$ROOT/skills/codegen-context/SKILL.md'"
assert "planner defaults to structured acceptance criteria" "rg -q 'structured acceptance criteria by default|measurable_post_condition' '$ROOT/agents/planner.md'"
assert "planner records legacy_ac and low-confidence escalate policy" "rg -q 'legacy_ac|task_classification_confidence < 0.6|human override' '$ROOT/agents/planner.md'"
assert "JIRA skill handles mixed acceptance criteria shapes" "rg -q 'Mixed Acceptance Criteria Shapes|\\.then|measurable_post_condition' '$ROOT/skills/jira-ticket-creation/SKILL.md'"
assert "Confluence skill handles mixed acceptance criteria shapes" "rg -q 'Mixed Acceptance Criteria Shapes|\\.then|measurable_post_condition' '$ROOT/skills/confluence-decomposition/SKILL.md'"
assert "DoD skill handles mixed acceptance criteria shapes" "rg -q 'Mixed Acceptance Criteria Shapes|\\.then|measurable_post_condition' '$ROOT/skills/definition-of-done/SKILL.md'"
assert "dag binding contract exists and marks gen_tests as an agent node" "rg -q 'DAG Binding Contract|WORKFLOW\\.md|gen_tests is now an agent node' '$ROOT/docs/specs/dag-binding.md'"
assert "triage implements confidence bands" "rg -q 'Confidence Bands|low_confidence|confidence_band|0.6 <= confidence < 0.8|< 0.6' '$ROOT/agents/triage.md'"
assert "applicability manifest spec documents confidence policy" "rg -q 'Confidence Policy|low_confidence|task_classification_confidence < 0.6' '$ROOT/docs/specs/applicability-manifest.md'"
assert "CASE-006 exists with escalate label and 0.55 confidence" "jq -e '.cases[] | select(.id==\"CASE-006\" and .expected_label==\"escalate\" and .expected_manifest.task_classification_confidence == 0.55)' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "CASE-007 exists with low_confidence label and 0.72 confidence" "jq -e '.cases[] | select(.id==\"CASE-007\" and .expected_label==\"low_confidence\" and .expected_manifest.task_classification_confidence == 0.72)' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "eval-council declares verifier scope intersection check" "rg -q 'Verifier Scope Intersection|verifier_no_coverage|target_files' '$ROOT/skills/eval-council/SKILL.md'"
assert "plan-reviewer output references verifier scope intersection" "rg -q 'verifier_scope_intersection|verifier_no_coverage' '$ROOT/agents/plan-reviewer.md'"
assert "test-strength skill exists with coverage and mutation thresholds" "[ -f '$ROOT/skills/test-strength/SKILL.md' ] && rg -q '0.8|0.6|mutmut|stryker|cargo-mutants|test_strength_report' '$ROOT/skills/test-strength/SKILL.md'"
assert "test-strength agent exists and maps to test_strength" "[ -f '$ROOT/agents/test-strength-auditor.md' ] && jq -e '.agents[] | select(.name==\"test-strength-auditor\") | .dag_node == \"test_strength\"' '$ROOT/skills/manifest.json' >/dev/null"
assert "WORKFLOW.dot includes test_strength node and weak edge" "rg -q 'test_strength \\[shape=box, label=\"Test Strength\\\\nCoverage \\+ Mutation Audit\", style=filled, fillcolor=\"#e6f3ff\"\\]' '$ROOT/WORKFLOW.dot' && rg -q 'qa -> test_strength.*label=\"pass\"' '$ROOT/WORKFLOW.dot' && rg -q 'test_strength -> fixer.*label=\"weak\"' '$ROOT/WORKFLOW.dot'"
assert "WORKFLOW.dot routes test_strength pass to slop_gate" "rg -q 'test_strength -> slop_gate.*label=\"pass\"' '$ROOT/WORKFLOW.dot'"
assert "WORKFLOW.md registers test_strength row and retry cap" "rg -q 'test_strength_retry: 2' '$ROOT/WORKFLOW.md' && rg -q 'agents/test-strength-auditor\\.md.*test-strength' '$ROOT/WORKFLOW.md'"
assert "WORKFLOW.md binds slop_gate command" "rg -q '^slop_gate:' '$ROOT/WORKFLOW.md' && rg -q 'stop-slop all --commit HEAD' '$ROOT/WORKFLOW.md'"
assert "manifest registers test-strength skill with consumes_manifest" "jq -e '.skills[] | select(.name==\"test-strength\") | .activation.consumes_manifest == true and (.activation.produces | index(\"test_strength_report\")) != null' '$ROOT/skills/manifest.json' >/dev/null"
assert "manifest registers triage low_confidence and planner escalate labels" "jq -e '.agents[] | select(.name==\"triage\") | (.labels | index(\"low_confidence\")) != null' '$ROOT/skills/manifest.json' >/dev/null && jq -e '.agents[] | select(.name==\"planner\") | (.labels | index(\"escalate\")) != null' '$ROOT/skills/manifest.json' >/dev/null"

echo ""
echo "--- LLM vs Deterministic Rebalance ---"
assert "llm-vs-deterministic spec exists" "[ -f '$ROOT/docs/specs/llm-vs-deterministic.md' ]"
assert "llm-vs-deterministic spec has at least 10 node rows" "awk '/^## Node Map$/{in_table=1; next} /^## Judge Inventory$/{in_table=0} in_table && /^\\|/{count++} END {exit !(count>=12)}' '$ROOT/docs/specs/llm-vs-deterministic.md'"
assert "llm-vs-deterministic spec lists per-judge cost guards" "rg -q 'Brief clarity|Specificity|Verifier semantic|Slop|Section policy|Mutant materiality' '$ROOT/docs/specs/llm-vs-deterministic.md' && rg -q '700 max tokens / call|900 max tokens / call|650 max tokens / call|750 max tokens / call|1400 max tokens / call' '$ROOT/docs/specs/llm-vs-deterministic.md'"
assert "all six judge skill files exist" "for f in '$ROOT/skills/brief-clarity-judge/SKILL.md' '$ROOT/skills/specificity-judge/SKILL.md' '$ROOT/skills/verifier-semantic-judge/SKILL.md' '$ROOT/skills/mutant-materiality-judge/SKILL.md' '$ROOT/skills/slop-judge/SKILL.md' '$ROOT/skills/section-policy-judge/SKILL.md'; do [ -f \"\$f\" ] || exit 1; done"
assert "judge skill frontmatter declares activation metadata" "for f in '$ROOT/skills/brief-clarity-judge/SKILL.md' '$ROOT/skills/specificity-judge/SKILL.md' '$ROOT/skills/verifier-semantic-judge/SKILL.md' '$ROOT/skills/mutant-materiality-judge/SKILL.md' '$ROOT/skills/slop-judge/SKILL.md' '$ROOT/skills/section-policy-judge/SKILL.md'; do rg -q '^activation:' \"\$f\" && rg -q 'model_class:' \"\$f\" && rg -q 'cost_guard:' \"\$f\" || exit 1; done"
assert "brief-clarity-judge registered with fast_judge metadata" "jq -e '.skills[] | select(.name==\"brief-clarity-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"fast_judge\" and .activation.cost_guard.max_tokens_per_call == 700' '$ROOT/skills/manifest.json' >/dev/null"
assert "specificity-judge registered with fast_judge metadata" "jq -e '.skills[] | select(.name==\"specificity-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"fast_judge\" and .activation.cost_guard.expected_calls_per_run == 4' '$ROOT/skills/manifest.json' >/dev/null"
assert "verifier-semantic-judge registered with fast_judge metadata" "jq -e '.skills[] | select(.name==\"verifier-semantic-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"fast_judge\" and .activation.cost_guard.max_tokens_per_call == 650' '$ROOT/skills/manifest.json' >/dev/null"
assert "mutant-materiality-judge registered with deep_judge metadata" "jq -e '.skills[] | select(.name==\"mutant-materiality-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"deep_judge\" and .activation.cost_guard.max_tokens_per_call == 1400' '$ROOT/skills/manifest.json' >/dev/null"
assert "slop-judge registered with fast_judge metadata" "jq -e '.skills[] | select(.name==\"slop-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"fast_judge\" and .activation.cost_guard.expected_calls_per_run == 3' '$ROOT/skills/manifest.json' >/dev/null"
assert "section-policy-judge registered with fast_judge metadata" "jq -e '.skills[] | select(.name==\"section-policy-judge\") | .activation.mode == \"judgement\" and .activation.model_class == \"fast_judge\" and .activation.cost_guard.expected_calls_per_run == 2' '$ROOT/skills/manifest.json' >/dev/null"
assert "every judge skill declares a cost guard" "jq -e 'all(.skills[] | select(.name==\"brief-clarity-judge\" or .name==\"specificity-judge\" or .name==\"verifier-semantic-judge\" or .name==\"mutant-materiality-judge\" or .name==\"slop-judge\" or .name==\"section-policy-judge\"); (.activation.cost_guard.max_tokens_per_call > 0) and (.activation.cost_guard.expected_calls_per_run >= 1))' '$ROOT/skills/manifest.json' >/dev/null"
assert "every modeled agent carries default fast_judge and deep_judge slots per runtime" "jq -e 'all(.agents[]; ((has(\"runtime_model_map\") | not) or ([.runtime_model_map.claude.default, .runtime_model_map.claude.fast_judge, .runtime_model_map.claude.deep_judge, .runtime_model_map.codex.default, .runtime_model_map.codex.fast_judge, .runtime_model_map.codex.deep_judge, .runtime_model_map.cursor.default, .runtime_model_map.cursor.fast_judge, .runtime_model_map.cursor.deep_judge, .runtime_model_map.antigravity.default, .runtime_model_map.antigravity.fast_judge, .runtime_model_map.antigravity.deep_judge, .runtime_model_map.factory.default, .runtime_model_map.factory.fast_judge, .runtime_model_map.factory.deep_judge] | all(type == \"string\"))))' '$ROOT/skills/manifest.json' >/dev/null"
assert "eval-council Gate 0 delegates presence checks to JSON schema" "rg -q 'Presence checks.*JSON schema validation|task_classification.*, change_surface.*, applicability_manifest.*, and verification_spec.*JSON schema validation' '$ROOT/skills/eval-council/SKILL.md'"
assert "eval-council Gate 0 references specificity-judge" "rg -q 'specificity-judge|low_specificity|specificity_judge_unavailable' '$ROOT/skills/eval-council/SKILL.md'"
assert "eval-council Gate 0 references verifier-semantic-judge" "rg -q 'verifier-semantic-judge|semantic change' '$ROOT/skills/eval-council/SKILL.md'"
assert "plan-reviewer supports stuck and low_specificity outputs" "rg -q 'labels: \\[lgtm, revise, blocked, stuck\\]' '$ROOT/agents/plan-reviewer.md' && rg -q 'low_specificity|specificity_judge_unavailable' '$ROOT/agents/plan-reviewer.md'"
assert "council verdict schema supports schema validation and specificity status fields" "jq -e '((.properties.verdict.properties.gate_0.required | index(\"schema_validation\")) != null) and ((.properties.verdict.properties.gate_0.required | index(\"specificity\")) != null)' '$ROOT/docs/schemas/council-verdict-output.schema.json' >/dev/null"
assert "council verdict schema uses rationale and failing_signals for specificity findings" "jq -e '((.properties.specificity_findings.items.required | index(\"rationale\")) != null) and ((.properties.specificity_findings.items.required | index(\"failing_signals\")) != null)' '$ROOT/docs/schemas/council-verdict-output.schema.json' >/dev/null"
assert "build-brief schema requires files_to_modify files_to_create and reference_impl" "jq -e '((.definitions.task.required | index(\"files_to_modify\")) != null) and ((.definitions.task.required | index(\"files_to_create\")) != null) and ((.definitions.task.required | index(\"reference_impl\")) != null)' '$ROOT/docs/schemas/build-brief.schema.json' >/dev/null"
assert "coder uses deterministic expected_failure_mode matching before LLM" "rg -q 'substring match|regex match|Levenshtein distance.*20%' '$ROOT/agents/coder.md'"
assert "test-strength-auditor is a wrapper with only materiality judge handoff" "rg -q 'tool-invocation wrapper|mutant-materiality-judge' '$ROOT/agents/test-strength-auditor.md'"
assert "test-strength skill marks material surviving mutants as weak" "rg -q 'material.*surviving mutant.*weak' '$ROOT/skills/test-strength/SKILL.md'"
assert "DoD tags checks as automatable or judgement" "awk -F'|' '(\$2 ~ /^[[:space:]]*[0-9]+[[:space:]]*$/) && (\$4 ~ /automatable/ || \$4 ~ /judgement/) {count++} END {exit !(count>=22)}' '$ROOT/skills/definition-of-done/SKILL.md'"
assert "stop-slop content mode routes through slop-judge with schema" "rg -q 'slop-judge|Slop Judge Input|Slop Judge Output' '$ROOT/skills/stop-slop/SKILL.md'"
assert "triage extracts signal features and low_confidence judge output" "rg -q 'Deterministic Feature Extraction|signal_features|low_confidence_judge' '$ROOT/agents/triage.md'"
assert "triage schema requires signal_features" "jq -e '((.required | index(\"signal_features\")) != null) and ((.properties.signal_features.required | index(\"reproducer_present\")) != null)' '$ROOT/docs/schemas/triage-output.schema.json' >/dev/null"
assert "applicability manifest spec documents section-policy override" "rg -q 'Section Policy Override|overridden_by: \"section_policy_judge\"' '$ROOT/docs/specs/applicability-manifest.md'"
assert "applicability manifest schema supports overridden_by" "jq -e '.properties.section_policy.items.properties.overridden_by.enum[0] == \"section_policy_judge\"' '$ROOT/docs/schemas/applicability-manifest.schema.json' >/dev/null"
assert "CASE-011 through CASE-018 exist with judge_calls" "jq -e '[.cases[] | select((.id | test(\"^CASE-01[1-8]$\")) and ((.expected_stage_outputs.judge_calls | length) == 6)) | .id] | unique | length == 8' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "judge_invocation evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/judge_invocation.sh' ]"
assert "run_backtest invokes judge_invocation evaluator" "rg -q 'judge_invocation' '$ROOT/tests/backtest/run_backtest.sh'"
assert "run_backtest serializes judge decisions into the report" "rg -q 'judge_decisions' '$ROOT/tests/backtest/run_backtest.sh'"
assert "smoke specificity fixture and assertion exist" "[ -f '$ROOT/tests/smoke/fixtures/feature_vague/.adlc/build_brief.json' ] && [ -x '$ROOT/tests/smoke/assertions/assert_specificity.sh' ] && [ -x '$ROOT/tests/smoke/stages/run_specificity.sh' ]"
assert "run_smoke includes the specificity stage" "rg -q 'run_stage_with_fixture .*specificity|artifacts/specificity\\.json' '$ROOT/tests/smoke/run_smoke.sh'"

echo ""
echo "--- Backtest Integrity ---"
assert "backtest runner exists and is executable" "[ -x '$ROOT/tests/backtest/run_backtest.sh' ]"
assert "triage evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/triage.sh' ]"
assert "section policy evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/section_policy.sh' ]"
assert "verifier scope evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/verifier_scope.sh' ]"
assert "DoD overlays evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/dod_overlays.sh' ]"
assert "council personas evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/council_personas.sh' ]"
assert "test strength evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/test_strength.sh' ]"
assert "judge invocation evaluator exists and is executable" "[ -x '$ROOT/tests/backtest/evaluators/judge_invocation.sh' ]"
assert "every fixture case declares expected_stage_outputs and rationale" "jq -e 'all(.cases[]; has(\"expected_stage_outputs\") and has(\"expected_rationale\"))' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "CASE-008 expects verifier scope revise" "jq -e '.cases[] | select(.id==\"CASE-008\") | .expected_stage_outputs.verifier_scope.verdict == \"revise\" and .expected_stage_outputs.verifier_scope.reason == \"verifier_no_coverage\"' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "CASE-009 expects weak test strength" "jq -e '.cases[] | select(.id==\"CASE-009\") | .expected_stage_outputs.test_strength.verdict == \"weak\" and .expected_stage_outputs.test_strength.coverage == 0.82 and .expected_stage_outputs.test_strength.mutation_kill_rate == 0.45' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "CASE-010 expects passing test strength" "jq -e '.cases[] | select(.id==\"CASE-010\") | .expected_stage_outputs.test_strength.verdict == \"pass\" and .expected_stage_outputs.test_strength.coverage == 0.85 and .expected_stage_outputs.test_strength.mutation_kill_rate == 0.7' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "backtest runner exits 0" "'$ROOT/tests/backtest/run_backtest.sh' >/dev/null 2>&1"
assert "backtest report parses" "jq empty '$ROOT/tests/backtest/last_report.json' >/dev/null 2>&1"
assert "backtest report covers every fixture case" "[ \"\$(jq -r '.cases | length' '$ROOT/tests/backtest/last_report.json')\" -eq \"\$(jq -r '.cases | length' '$ROOT/tests/fixtures/applicability-issue-set.json')\" ]"
assert "backtest report records judge decisions per case" "jq -e 'all(.cases[]; (.judge_decisions | type) == \"array\" and (.judge_decisions | length) == 6)' '$ROOT/tests/backtest/last_report.json' >/dev/null"
assert "backtest report records zero failures" "jq -e '.failed == 0 and .passed == .total' '$ROOT/tests/backtest/last_report.json' >/dev/null"
assert "backtest total entries cover the seven-stage matrix" "[ \"\$(jq -r '.total' '$ROOT/tests/backtest/last_report.json')\" -eq \"\$(jq -r '.cases | length * 7' '$ROOT/tests/fixtures/applicability-issue-set.json')\" ]"

echo ""
echo "--- Smoke Harness Integrity ---"
assert "smoke runner exists and is executable" "[ -x '$ROOT/tests/smoke/run_smoke.sh' ]"
assert "smoke build brief parses" "jq empty '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' >/dev/null 2>&1"
assert "smoke applicability manifest parses and satisfies required schema fields" "jq -e '.version == \"1.0.0\" and .task_classification == \"feature\" and .task_classification_confidence == 0.92 and (.change_surface.runtime_path_change == true) and (.change_surface.user_facing_operation == true) and (.verification_spec.primary_verifier.target_files[0] == \"src/scoreboard.py\")' '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/applicability_manifest.json' >/dev/null"
assert "smoke expected directory has five JSON files and they parse" "[ \"\$(find '$ROOT/tests/smoke/fixtures/feature_bugfix/expected' -maxdepth 1 -name '*.json' | wc -l | tr -d ' ')\" -eq 5 ] && jq empty '$ROOT/tests/smoke/fixtures/feature_bugfix/expected/'*.json >/dev/null 2>&1"
assert "every smoke stage script is executable" "! find '$ROOT/tests/smoke/stages' -maxdepth 1 -name '*.sh' ! -perm -111 | grep -q ."
assert "every smoke assertion script is executable" "! find '$ROOT/tests/smoke/assertions' -maxdepth 1 -name '*.sh' ! -perm -111 | grep -q ."
assert "smoke stages README exists" "[ -f '$ROOT/tests/smoke/stages/README.md' ]"
assert "smoke artifacts path is gitignored" "rg -q 'tests/smoke/artifacts/\\*|tests/smoke/artifacts/' '$ROOT/.gitignore'"
assert "run_smoke without SMOKE=1 exits non-zero with explanatory message" "tmp=\$(mktemp); if '$ROOT/tests/smoke/run_smoke.sh' >\"\$tmp\" 2>&1; then ok=1; else ok=0; fi; if [ \"\$ok\" -ne 0 ]; then rm -f \"\$tmp\"; false; else rg -q 'SMOKE=1' \"\$tmp\"; status=\$?; rm -f \"\$tmp\"; [ \"\$status\" -eq 0 ]; fi"
assert "run_smoke without SMOKE=1 does not mention claude invocation" "tmp=\$(mktemp); '$ROOT/tests/smoke/run_smoke.sh' >\"\$tmp\" 2>&1 || true; if rg -q 'claude --|\\bclaude\\b' \"\$tmp\"; then rm -f \"\$tmp\"; false; else rm -f \"\$tmp\"; true; fi"

echo ""
echo "--- Smoke Invocation Hardening ---"
assert "_invoke helper exists and is executable" "[ -x '$ROOT/tests/smoke/stages/_invoke.sh' ]"
assert "_validate helper exists and is executable" "[ -x '$ROOT/tests/smoke/stages/_validate.sh' ]"
assert "specificity smoke stage and assertion exist" "[ -x '$ROOT/tests/smoke/stages/run_specificity.sh' ] && [ -x '$ROOT/tests/smoke/assertions/assert_specificity.sh' ]"
assert "triage agent has output contract section" "rg -q '^## Output Contract$' '$ROOT/agents/triage.md'"
assert "test-author agent has output contract section" "rg -q '^## Output Contract$' '$ROOT/agents/test-author.md'"
assert "coder agent has output contract section" "rg -q '^## Output Contract$' '$ROOT/agents/coder.md'"
assert "test-strength agent has output contract section" "rg -q '^## Output Contract$' '$ROOT/agents/test-strength-auditor.md'"
assert "plan-reviewer agent has output contract section" "rg -q '^## Output Contract$' '$ROOT/agents/plan-reviewer.md'"
assert "all five smoke output schemas parse" "jq empty '$ROOT/docs/schemas/triage-output.schema.json' '$ROOT/docs/schemas/test-author-output.schema.json' '$ROOT/docs/schemas/coder-output.schema.json' '$ROOT/docs/schemas/test-strength-output.schema.json' '$ROOT/docs/schemas/council-verdict-output.schema.json' >/dev/null 2>&1"
assert "all five smoke output schemas declare required arrays with at least three entries" "jq -e '(.required | type) == \"array\" and (.required | length) >= 3' '$ROOT/docs/schemas/triage-output.schema.json' >/dev/null && jq -e '(.required | type) == \"array\" and (.required | length) >= 3' '$ROOT/docs/schemas/test-author-output.schema.json' >/dev/null && jq -e '(.required | type) == \"array\" and (.required | length) >= 3' '$ROOT/docs/schemas/coder-output.schema.json' >/dev/null && jq -e '(.required | type) == \"array\" and (.required | length) >= 3' '$ROOT/docs/schemas/test-strength-output.schema.json' >/dev/null && jq -e '(.required | type) == \"array\" and (.required | length) >= 3' '$ROOT/docs/schemas/council-verdict-output.schema.json' >/dev/null"
assert "stage scripts source _invoke helper" "for f in '$ROOT/tests/smoke/stages/run_triage.sh' '$ROOT/tests/smoke/stages/run_spec_to_tests.sh' '$ROOT/tests/smoke/stages/run_coder.sh' '$ROOT/tests/smoke/stages/run_test_strength.sh' '$ROOT/tests/smoke/stages/run_council.sh'; do rg -q '_invoke\\.sh' \"\$f\" || exit 1; done"
assert "specificity stage sources _invoke helper" "rg -q '_invoke\\.sh' '$ROOT/tests/smoke/stages/run_specificity.sh'"
assert "_invoke helper is a runtime dispatcher without inline CLI flags" "! rg -q 'claude --|codex exec|--system-prompt|--bare|--json-schema|--output-schema|command -v (claude|codex|cursor|gemini|antigravity|factory)' '$ROOT/tests/smoke/stages/_invoke.sh'"
assert "stage scripts pass explicit tool grants into invoke_agent" "rg -q -- '--tools \"\"' '$ROOT/tests/smoke/stages/run_triage.sh' && rg -q -- '--tools \"Read,Write,Bash\"' '$ROOT/tests/smoke/stages/run_spec_to_tests.sh' && rg -q -- '--tools \"Read,Write,Edit,Bash,Glob,Grep\"' '$ROOT/tests/smoke/stages/run_coder.sh' && rg -q -- '--tools \"Read,Bash\"' '$ROOT/tests/smoke/stages/run_test_strength.sh' && rg -q -- '--tools \"\"' '$ROOT/tests/smoke/stages/run_council.sh' && rg -q -- '--tools \"\"' '$ROOT/tests/smoke/stages/run_specificity.sh'"
assert "triage stage makes workspace read-only before invocation" "rg -q 'chmod -R a-w ' '$ROOT/tests/smoke/stages/run_triage.sh' && rg -q 'workspace_dir' '$ROOT/tests/smoke/stages/run_triage.sh'"
assert "council stage makes workspace read-only before invocation" "rg -q 'chmod -R a-w ' '$ROOT/tests/smoke/stages/run_council.sh' && rg -q 'workspace_dir' '$ROOT/tests/smoke/stages/run_council.sh'"
assert "run_smoke recreates a fresh workspace copy at the start of each stage" "rg -q 'prepare_workspace ' '$ROOT/tests/smoke/run_smoke.sh' && rg -q 'cp -R ' '$ROOT/tests/smoke/run_smoke.sh' && rg -q 'source_dir' '$ROOT/tests/smoke/run_smoke.sh' && rg -q 'WORKSPACE_DIR' '$ROOT/tests/smoke/run_smoke.sh'"
assert "golden smoke report is tracked" "git -C '$ROOT' ls-files --error-unmatch 'tests/smoke/artifacts/smoke_report.json' >/dev/null 2>&1"
assert "golden smoke report records a passing run" "jq -e '.overall == \"pass\"' '$ROOT/tests/smoke/artifacts/smoke_report.json' >/dev/null 2>&1"

echo ""
echo "--- Runtime-Agnostic Smoke Dispatch ---"
assert "_invoke dispatcher sources runtime adapters" "rg -Fq 'adapters/\${runtime}.sh' '$ROOT/tests/smoke/stages/_invoke.sh' && rg -Fq 'source \"\$adapter_path\"' '$ROOT/tests/smoke/stages/_invoke.sh'"
assert "all smoke adapters exist and are executable" "for f in '$ROOT/tests/smoke/adapters/claude.sh' '$ROOT/tests/smoke/adapters/codex.sh' '$ROOT/tests/smoke/adapters/cursor.sh' '$ROOT/tests/smoke/adapters/antigravity.sh' '$ROOT/tests/smoke/adapters/factory.sh'; do [ -x \"\$f\" ] || exit 1; done"
assert "all adapter headers declare runtime metadata markers" "for f in '$ROOT/tests/smoke/adapters/claude.sh' '$ROOT/tests/smoke/adapters/codex.sh' '$ROOT/tests/smoke/adapters/cursor.sh' '$ROOT/tests/smoke/adapters/antigravity.sh' '$ROOT/tests/smoke/adapters/factory.sh'; do rg -q '^# Runtime:' \"\$f\" && rg -q '^# Minimum CLI Version:' \"\$f\" && rg -q '^# Auth Env Vars:' \"\$f\" && rg -q '^# Flag Mapping:' \"\$f\" && rg -q '^# Known Limitations:' \"\$f\" || exit 1; done"
assert "unsupported runtime fails with a clear message" "tmp=\$(mktemp); if env -i PATH='/usr/bin:/bin' ADLC_RUNTIME='unsupported' /bin/bash -c 'source \"\$1\"; preflight' bash '$ROOT/tests/smoke/stages/_invoke.sh' >\"\$tmp\" 2>&1; then status=0; else status=\$?; fi; ok=0; if [ \"\$status\" -ne 0 ] && rg -q 'unsupported runtime' \"\$tmp\"; then ok=1; fi; rm -f \"\$tmp\"; [ \"\$ok\" -eq 1 ]"
assert "each adapter preflight without auth exits 65" "for runtime in claude codex cursor antigravity factory; do if env -i PATH='/usr/bin:/bin' /bin/bash '$ROOT/tests/smoke/adapters/'\"\$runtime\"'.sh' preflight >/dev/null 2>&1; then exit 1; else [ \"\$?\" -eq 65 ] || exit 1; fi; done"
assert "adapter dispatch test exists and is executable" "[ -x '$ROOT/tests/smoke/adapters/test_dispatch.sh' ]"
assert "adapter dispatch test passes" "'$ROOT/tests/smoke/adapters/test_dispatch.sh' >/dev/null 2>&1"
assert "WORKFLOW.md backends list all five runtimes" "rg -q '^  claude:$' '$ROOT/WORKFLOW.md' && rg -q '^  codex:$' '$ROOT/WORKFLOW.md' && rg -q '^  cursor:$' '$ROOT/WORKFLOW.md' && rg -q '^  antigravity:$' '$ROOT/WORKFLOW.md' && rg -q '^  factory:$' '$ROOT/WORKFLOW.md'"
assert "WORKFLOW.md backend commands route through smoke adapters" "rg -q 'tests/smoke/adapters/claude\\.sh invoke_agent' '$ROOT/WORKFLOW.md' && rg -q 'tests/smoke/adapters/codex\\.sh invoke_agent' '$ROOT/WORKFLOW.md' && rg -q 'tests/smoke/adapters/cursor\\.sh invoke_agent' '$ROOT/WORKFLOW.md' && rg -q 'tests/smoke/adapters/antigravity\\.sh invoke_agent' '$ROOT/WORKFLOW.md' && rg -q 'tests/smoke/adapters/factory\\.sh invoke_agent' '$ROOT/WORKFLOW.md'"
assert "dag binding references smoke adapters as invocation source of truth" "rg -q 'tests/smoke/adapters/' '$ROOT/docs/specs/dag-binding.md' && rg -q 'WORKFLOW\\.md.*backends' '$ROOT/docs/specs/dag-binding.md'"
assert "smoke README documents all five runtime commands" "rg -q 'ADLC_RUNTIME=claude' '$ROOT/tests/smoke/README.md' && rg -q 'ADLC_RUNTIME=codex' '$ROOT/tests/smoke/README.md' && rg -q 'ADLC_RUNTIME=antigravity' '$ROOT/tests/smoke/README.md' && rg -q 'ADLC_RUNTIME=cursor' '$ROOT/tests/smoke/README.md' && rg -q 'ADLC_RUNTIME=factory' '$ROOT/tests/smoke/README.md'"
assert "run_smoke uses adapter preflight and ADLC_RUNTIME" "rg -Fq 'ADLC_RUNTIME:-claude' '$ROOT/tests/smoke/run_smoke.sh' && rg -Fq 'AUTH_PATH=\"\$(preflight)\"' '$ROOT/tests/smoke/run_smoke.sh'"
assert "manifest carries runtime_model_map on every modeled agent" "jq -e 'all(.agents[]; (has(\"model\") | not) or ((.runtime_model_map | type) == \"object\" and (.runtime_model_map | has(\"claude\")) and (.runtime_model_map | has(\"codex\")) and (.runtime_model_map | has(\"cursor\")) and (.runtime_model_map | has(\"antigravity\")) and (.runtime_model_map | has(\"factory\"))))' '$ROOT/skills/manifest.json' >/dev/null"

echo ""
echo "--- Truthfulness ---"
assert "setup script does not hardcode 22 skills" "! rg -q '22 skills' '$ROOT/setup.sh'"
assert "platform CLAUDE doc does not hardcode 22 skills" "! rg -q '22 skills' '$ROOT/platform/CLAUDE.md'"
assert "platform AGENTS doc does not hardcode 22 skills" "! rg -q '22 injectable skills|22 skills' '$ROOT/platform/AGENTS.md'"
assert "setup test does not expect 22 skills" "! rg -q \"'22'|22 skills\" '$ROOT/tests/test_setup.sh'"
assert "README avoids stale headline inventory claim" "! rg -q '^11 agents\\. 34 skills\\.' '$ROOT/README.md'"
assert "platform CLAUDE doc avoids RED/GREEN/REFACTOR" "! rg -q 'RED/GREEN/REFACTOR' '$ROOT/platform/CLAUDE.md'"
assert "agents antigravity doc avoids RED/GREEN/REFACTOR" "! rg -q 'RED/GREEN/REFACTOR' '$ROOT/platform/agents-antigravity.md'"
assert "workflow diagram uses verifier-led wording" "rg -q 'Verifier-led execution|Author Failing Tests / Reproducers|Tests / Reproducers / Failing Commands' '$ROOT/WORKFLOW.dot'"

echo ""
echo "--- Issue Benchmark ---"
assert "issue set contains eighteen benchmark cases" "jq -e '.cases | length == 18' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "issue set covers build_validation" "jq -e '.cases[] | select(.expected_manifest.task_classification==\"build_validation\")' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "issue set covers lint_cleanup" "jq -e '.cases[] | select(.expected_manifest.task_classification==\"lint_cleanup\")' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "issue set covers bugfix" "jq -e '.cases[] | select(.expected_manifest.task_classification==\"bugfix\")' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "issue set covers feature" "jq -e '.cases[] | select(.expected_manifest.task_classification==\"feature\")' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "issue set covers security-sensitive work" "jq -e '.cases[] | select(.expected_manifest.task_classification==\"security\")' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "build validation suppresses security and observability" "jq -e '.cases[] | select(.id==\"CASE-001\") | (.expected_manifest.section_policy | any(.section_name==\"5_security_review\" and .status==\"suppressed\")) and (.expected_manifest.section_policy | any(.section_name==\"6_observability_slo\" and .status==\"suppressed\"))' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "lint cleanup uses command verifier" "jq -e '.cases[] | select(.id==\"CASE-002\") | .expected_manifest.verification_spec.primary_verifier.type == \"command\"' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "bugfix case flags contamination" "jq -e '.cases[] | select(.id==\"CASE-003\") | (.expected_manifest.contamination.flags | index(\"unsupported_claim\")) != null' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"
assert "security feature activates security review" "jq -e '.cases[] | select(.id==\"CASE-005\") | (.expected_manifest.section_policy | any(.section_name==\"5_security_review\" and .status==\"active\"))' '$ROOT/tests/fixtures/applicability-issue-set.json' >/dev/null"

echo ""
echo "═══════════════════════════════════════"
echo -e "Results: ${GREEN}$PASS passed${NC}, ${RED}$FAIL failed${NC}, $TOTAL total"
echo "═══════════════════════════════════════"

[ "$FAIL" -eq 0 ] && exit 0 || exit 1
