#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0
FAIL=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

assert() {
  local desc="$1"
  local condition="$2"
  TOTAL=$((TOTAL + 1))
  if eval "$condition"; then
    printf '  %bPASS%b %s\n' "$GREEN" "$NC" "$desc"
    PASS=$((PASS + 1))
  else
    printf '  %bFAIL%b %s\n' "$RED" "$NC" "$desc"
    FAIL=$((FAIL + 1))
  fi
}

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
mkdir -p "$tmp_dir/workflow" "$tmp_dir/emitter" "$tmp_dir/no-solutions"

echo "ADLC CLI Tests"
echo "Root: $ROOT"
echo ""

echo "--- Discovery ---"
assert "CLI wrapper exists and is executable" "[ -x '$ROOT/bin/adlc' ]"
assert "list-agents emits JSON with planner" "'$ROOT/bin/adlc' list-agents --json | jq -e '.count >= 11 and any(.agents[]; .name == \"planner\" and .dag_node == \"plan\")' >/dev/null"
assert "list-phases emits workflow nodes and edges" "'$ROOT/bin/adlc' list-phases --json | jq -e '.count >= 17 and any(.nodes[]; .id == \"compound_preflight\" and .type == \"tool\") and any(.nodes[]; .id == \"learning_capture\" and .type == \"tool\") and any(.edges[]; .from == \"triage\" and .to == \"compound_preflight\") and any(.edges[]; .from == \"compound_preflight\" and .to == \"research\")' >/dev/null"
assert "list-phases emits readable text" "'$ROOT/bin/adlc' list-phases | rg -q '^plan[[:space:]]+agent[[:space:]]+planner'"

echo ""
echo "--- Schema Validation ---"
assert "validate-artifact accepts smoke build brief" "'$ROOT/bin/adlc' validate-artifact --schema build-brief --input '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts loop contract fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-contract --input '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts loop action fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-action --input '$ROOT/tests/fixtures/loop_maturity/valid-loop-action.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts loop test result fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-test-result --input '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts loop maturity report fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-maturity-report --input '$ROOT/tests/fixtures/loop_maturity/assisted-loop-report.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts token budget fixture" "'$ROOT/bin/adlc' validate-artifact --schema token-budget --input '$ROOT/tests/fixtures/loop_maturity/token-budget-healthy.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts budgeted loop contract fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-contract --input '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts budgeted loop action fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-action --input '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact accepts budgeted loop maturity report fixture" "'$ROOT/bin/adlc' validate-artifact --schema loop-maturity-report --input '$ROOT/tests/fixtures/loop_maturity/budgeted-maturity-report.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
assert "validate-artifact rejects invalid loop contract" "if '$ROOT/bin/adlc' validate-artifact --schema loop-contract --input '$ROOT/tests/fixtures/loop_maturity/invalid-missing-test-floor.json' --json >'$tmp_dir/invalid-loop-contract.json' 2>/dev/null; then false; else jq -e '.valid == false and any(.errors[]; contains(\"mandatory_floor\"))' '$tmp_dir/invalid-loop-contract.json' >/dev/null; fi"
jq 'del(.adlc_mode)' "$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json" > "$tmp_dir/invalid-build-brief.json"
assert "validate-artifact rejects missing required field" "if '$ROOT/bin/adlc' validate-artifact --schema build-brief --input '$tmp_dir/invalid-build-brief.json' --json >'$tmp_dir/invalid-result.json' 2>/dev/null; then false; else jq -e '.valid == false and any(.errors[]; contains(\"adlc_mode\"))' '$tmp_dir/invalid-result.json' >/dev/null; fi"

echo ""
echo "--- Compound Context ---"
assert "health-check passes required runtime checks" "'$ROOT/bin/adlc' health-check --json | jq -e '.status == \"pass\" and .summary.failed_required == 0 and any(.checks[]; .name == \"jsonschema\" and .status == \"pass\") and any(.checks[]; .name == \"schemas\" and .status == \"pass\")' >/dev/null"
assert "compound-context no-ops cleanly without learning store" "'$ROOT/bin/adlc' compound-context --workspace '$tmp_dir/no-solutions' --json | jq -e '.contract_version == \"1.0.0\" and .summary.learning_refs == 0 and (.no_op_reasons | index(\"docs/solutions not found\")) != null' >/dev/null"
mkdir -p "$tmp_dir/compound/docs/solutions"
cp "$ROOT/tests/fixtures/learning-entry-knowledge.md" "$tmp_dir/compound/docs/solutions/ref.md"
assert "compound-context emits compact learning refs" "'$ROOT/bin/adlc' compound-context --workspace '$tmp_dir/compound' --input 'compound context learning refs' --json | jq -e '.summary.learning_refs == 1 and (.learning_refs[0].path | endswith(\"/compound/docs/solutions/ref.md\")) and (.learning_refs[0].summary | length) > 0 and (.learning_refs[0] | has(\"verifier\"))' >/dev/null"
assert "compound-context emits Build Brief task and verifier refs" "'$ROOT/bin/adlc' compound-context --workspace '$ROOT' --build-brief '$ROOT/docs/build-briefs/compound-engineering-workflow-integration.json' --json | jq -e '.summary.task_refs == 7 and .summary.verifier_refs == 7 and any(.task_refs[]; .task_id == \"ADLC-CEI-004\")' >/dev/null"

echo ""
echo "--- Workflow Runner ---"
assert "run dry-run creates workflow state and advances start to triage" "'$ROOT/bin/adlc' run --brief-id CLI-WF --workspace '$tmp_dir/workflow' --dry-run --json | jq -e '.state.brief_id == \"CLI-WF\" and .state.phase == \"triage\" and .state.status == \"planned\" and (.state.checkpoint.history | length) == 1' >/dev/null"
assert "run-phase dry-run advances triage to compound preflight" "'$ROOT/bin/adlc' run-phase --workspace '$tmp_dir/workflow' --dry-run --json | jq -e '.state.phase == \"compound_preflight\" and .state.status == \"planned\" and (.state.checkpoint.history[-1].phase == \"triage\")' >/dev/null"
assert "resume-workflow increments resume count and reports next action" "'$ROOT/bin/adlc' resume-workflow --workspace '$tmp_dir/workflow' --json | jq -e '.state.resume_count == 1 and .next_action.phase == \"compound_preflight\" and .next_action.runnable == true and .next_action.task_resume_status.total == 0' >/dev/null"
assert "run-phase dry-run advances compound preflight to research" "'$ROOT/bin/adlc' run-phase --workspace '$tmp_dir/workflow' --dry-run --json | jq -e '.state.phase == \"research\" and .state.status == \"planned\" and (.state.checkpoint.history[-1].phase == \"compound_preflight\")' >/dev/null"
jq '.task_fingerprints = [{"task_id":"SMOKE_FEATURE_SCOREBOARD","input_hash":"abc123","status":"failed","primary_verifier":"pytest tests/test_scoreboard.py","pre_change_status":"failed_expected","post_change_status":"failed","changed_files":["src/scoreboard.py"],"commit":null,"evidence":["pytest failed"]}]' "$tmp_dir/workflow/.adlc/workflow_state.json" > "$tmp_dir/workflow-state-with-fingerprints.json"
mv "$tmp_dir/workflow-state-with-fingerprints.json" "$tmp_dir/workflow/.adlc/workflow_state.json"
assert "resume-workflow reports incomplete task fingerprints" "'$ROOT/bin/adlc' resume-workflow --workspace '$tmp_dir/workflow' --json | jq -e '.next_action.task_resume_status.total == 1 and .next_action.task_resume_status.counts.failed == 1 and .next_action.task_resume_status.incomplete[0].task_id == \"SMOKE_FEATURE_SCOREBOARD\"' >/dev/null"
assert "workflow state validates against schema" "'$ROOT/bin/adlc' validate-artifact --schema workflow-state --input '$tmp_dir/workflow/.adlc/workflow_state.json' --json | jq -e '.valid == true and (.errors | length) == 0' >/dev/null"
cp "$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json" "$tmp_dir/loop-workflow-state.json"
assert "resume-workflow reports loop progress and control state" "'$ROOT/bin/adlc' resume-workflow --state '$tmp_dir/loop-workflow-state.json' --json | jq -e '.next_action.loop_progress.last_progress_signal == \"resolved_missing_required_test\" and .next_action.no_progress_count == 0 and .next_action.control_events[0].event_type == \"steer\" and .next_action.safe_checkpoint.idempotent == true and .next_action.escalation_context.no_progress_after == 2' >/dev/null"
cp "$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json" "$tmp_dir/loop-workflow-state-budget.json"
assert "resume-workflow reports loop budget status" "'$ROOT/bin/adlc' resume-workflow --state '$tmp_dir/loop-workflow-state-budget.json' --json | jq -e '.next_action.budget_status.status == \"healthy\" and .next_action.budget_status.decision == \"proceed\" and .next_action.budget_status.token_budget_ref == \"tests/fixtures/loop_maturity/token-budget-healthy.json\"' >/dev/null"

echo ""
echo "--- Loop System Maturity ---"
assert "loop-test-selection passes complete required plan" "'$ROOT/bin/adlc' loop-test-selection --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --json | jq -e '.status == \"pass\" and (.missing_required_tests | length) == 0 and (.provided_required_tests | index(\"required:test-selection\")) != null' >/dev/null"
assert "loop-test-selection passes strict executed required results" "'$ROOT/bin/adlc' loop-test-selection --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --require-test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --json | jq -e '.status == \"pass\" and (.missing_executed_required_tests | length) == 0 and (.executed_required_tests | index(\"required:test-selection\")) != null' >/dev/null"
assert "loop-test-selection blocks missing executed required results" "if '$ROOT/bin/adlc' loop-test-selection --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --require-test-results '$ROOT/tests/fixtures/loop_maturity/test-results-missing-required.json' --json >'$tmp_dir/loop-tests-missing-results.json' 2>/dev/null; then false; else jq -e '.status == \"blocked\" and (.missing_executed_required_tests | index(\"required:test-selection\")) != null and any(.issues[]; .rule == \"missing_executed_required_tests\")' '$tmp_dir/loop-tests-missing-results.json' >/dev/null; fi"
assert "loop-test-selection blocks missing required tests" "if '$ROOT/bin/adlc' loop-test-selection --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-missing-required.json' --json >'$tmp_dir/loop-tests-missing.json' 2>/dev/null; then false; else jq -e '.status == \"blocked\" and (.missing_required_tests | index(\"required:test-selection\")) != null and any(.issues[]; .rule == \"missing_required_tests\")' '$tmp_dir/loop-tests-missing.json' >/dev/null; fi"
assert "loop-budget-check proceeds on healthy budget" "'$ROOT/bin/adlc' loop-budget-check --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-healthy.json' --estimated-input-tokens 10 --expected-output-tokens 10 --phase phase_5_codegen_context --skill codegen-context --json | jq -e '.status == \"proceed\" and .budget_status.status == \"healthy\" and .projected_total == 1020 and .budget_remaining == 98980' >/dev/null"
assert "loop-budget-check warns on warning budget" "'$ROOT/bin/adlc' loop-budget-check --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-warning.json' --estimated-input-tokens 10 --expected-output-tokens 10 --phase phase_5_codegen_context --skill codegen-context --json | jq -e '.status == \"warning\" and .budget_status.status == \"warning\"' >/dev/null"
assert "loop-budget-check wraps up on alert threshold" "'$ROOT/bin/adlc' loop-budget-check --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-warning.json' --estimated-input-tokens 30000 --expected-output-tokens 0 --phase phase_5_codegen_context --skill codegen-context --json | jq -e '.status == \"wrap_up\" and .budget_status.status == \"alert\" and .threshold == \"alert_at\"' >/dev/null"
assert "loop-budget-check blocks exhausted budget" "if '$ROOT/bin/adlc' loop-budget-check --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-exhausted.json' --estimated-input-tokens 10 --expected-output-tokens 10 --phase phase_5_codegen_context --skill codegen-context --json >'$tmp_dir/loop-budget-exhausted.json' 2>/dev/null; then false; else jq -e '.status == \"blocked\" and .stop_reason == \"budget_exhausted\" and .budget_status.status == \"exhausted\"' '$tmp_dir/loop-budget-exhausted.json' >/dev/null; fi"
assert "loop-budget-check blocks stale budget" "if '$ROOT/bin/adlc' loop-budget-check --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-stale.json' --estimated-input-tokens 10 --expected-output-tokens 10 --phase phase_5_codegen_context --skill codegen-context --json >'$tmp_dir/loop-budget-stale.json' 2>/dev/null; then false; else jq -e '.status == \"blocked\" and .stop_reason == \"budget_stale\" and .budget_status.status == \"stale\"' '$tmp_dir/loop-budget-stale.json' >/dev/null; fi"
assert "loop-action-validate admits allowed action" "'$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/valid-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json' --json | jq -e '.status == \"admitted\" and .action_id == \"action:run-required-test-selection\"' >/dev/null"
assert "loop-action-validate admits budgeted action with healthy budget" "'$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-healthy.json' --json | jq -e '.status == \"admitted\" and .budget_status.status == \"healthy\" and .budget_check.status == \"proceed\"' >/dev/null"
assert "loop-action-validate resolves contract budget guard ref" "'$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --json | jq -e '.status == \"admitted\" and .budget_status.token_budget_ref == \"tests/fixtures/loop_maturity/token-budget-healthy.json\" and .budget_check.status == \"proceed\"' >/dev/null"
assert "loop-action-validate rejects exhausted budget before execution" "if '$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-exhausted.json' --json >'$tmp_dir/loop-action-budget-rejected.json' 2>/dev/null; then false; else jq -e '.status == \"rejected\" and .budget_status.status == \"exhausted\" and any(.issues[]; .rule == \"budget_exhausted\")' '$tmp_dir/loop-action-budget-rejected.json' >/dev/null; fi"
assert "loop-action-validate rejects skipped required tests" "if '$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/rejected-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json' --json >'$tmp_dir/loop-action-rejected.json' 2>/dev/null; then false; else jq -e '.status == \"rejected\" and any(.issues[]; .rule == \"action_skips_required_tests\" and (.missing_required_tests | index(\"required:test-selection\")))' '$tmp_dir/loop-action-rejected.json' >/dev/null; fi"
assert "loop-action-validate routes escalation with context" "'$ROOT/bin/adlc' loop-action-validate --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --action '$ROOT/tests/fixtures/loop_maturity/escalate-loop-action.json' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json' --json | jq -e '.status == \"escalate\" and .escalation_context.no_progress_after == 2' >/dev/null"
assert "loop-maturity-audit caps tag-only test selection score" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/valid-loop-action.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .dimension_scores.test_selection_cannot_be_gamed.score == 2 and (.dimension_scores.test_selection_cannot_be_gamed.missing_mechanisms | index(\"executed required-test evidence\")) != null' >/dev/null"
assert "loop-maturity-audit emits schema-valid execution-backed assisted-loop report" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-control-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/valid-loop-action.json' --output '$tmp_dir/generated-loop-report.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .action_admission.status == \"admitted\" and .dimension_scores.test_selection_cannot_be_gamed.score == 3' >/dev/null && '$ROOT/bin/adlc' validate-artifact --schema loop-maturity-report --input '$tmp_dir/generated-loop-report.json' --json | jq -e '.valid == true' >/dev/null"
assert "loop-maturity-audit emits budget status with healthy budget" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-healthy.json' --output '$tmp_dir/generated-budgeted-loop-report.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .budget_status.status == \"healthy\" and .budget_status.decision == \"proceed\"' >/dev/null && '$ROOT/bin/adlc' validate-artifact --schema loop-maturity-report --input '$tmp_dir/generated-budgeted-loop-report.json' --json | jq -e '.valid == true' >/dev/null"
assert "loop-maturity-audit resolves contract budget guard ref" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .budget_status.token_budget_ref == \"tests/fixtures/loop_maturity/token-budget-healthy.json\" and .budget_status.status == \"healthy\"' >/dev/null"
assert "loop-maturity-audit allows self-autonomous only with healthy budget evidence" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/self-autonomous-budgeted-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-healthy.json' --json | jq -e '.maturity_verdict == \"self_autonomous\" and .budget_status.status == \"healthy\"' >/dev/null"
assert "loop-maturity-audit downgrades self-autonomous warning budget" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$ROOT/tests/fixtures/loop_maturity/self-autonomous-budgeted-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --token-budget '$ROOT/tests/fixtures/loop_maturity/token-budget-warning.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .budget_status.status == \"warning\" and (.prioritized_gaps.blocks_autonomy[0] | contains(\"Loop Budget Guard\"))' >/dev/null"
jq 'del(.budget_guard)' "$ROOT/tests/fixtures/loop_maturity/self-autonomous-budgeted-contract.json" > "$tmp_dir/self-autonomous-missing-budget-contract.json"
assert "loop-maturity-audit downgrades self-autonomous missing budget" "'$ROOT/bin/adlc' loop-maturity-audit --loop-contract '$tmp_dir/self-autonomous-missing-budget-contract.json' --workflow '$ROOT/WORKFLOW.dot' --state '$ROOT/tests/fixtures/loop_maturity/workflow-state-budget-progress.json' --test-plan '$ROOT/tests/fixtures/loop_maturity/test-plan-complete-required.json' --test-results '$ROOT/tests/fixtures/loop_maturity/test-results-complete-required.json' --action '$ROOT/tests/fixtures/loop_maturity/budgeted-loop-action.json' --json | jq -e '.maturity_verdict == \"assisted_loop\" and .budget_status.status == \"missing\" and .budget_status.stop_reason == \"budget_missing\"' >/dev/null"
assert "loop-maturity-audit help exposes test-results and omits dead build-brief flag" "'$ROOT/bin/adlc' loop-maturity-audit --help >'$tmp_dir/loop-maturity-help.txt' && rg -q -- '--test-results' '$tmp_dir/loop-maturity-help.txt' && ! rg -q -- '--build-brief' '$tmp_dir/loop-maturity-help.txt'"

echo ""
echo "--- Work-Item Emitters ---"
provider="$tmp_dir/provider.sh"
cat > "$provider" <<'SH'
#!/usr/bin/env bash
jq '{status:"completed", artifact_count:(.artifacts | length), artifacts:(.artifacts | map({idempotency_key, artifact_id: ("LIN-" + .id), artifact_ref: ("linear://LIN-" + .id)}))}'
SH
chmod +x "$provider"
partial_provider="$tmp_dir/partial-provider.sh"
cat > "$partial_provider" <<'SH'
#!/usr/bin/env bash
jq '{status:"completed", artifacts:(.artifacts | map(if .id == "SMOKE_FEATURE_SCOREBOARD" then {idempotency_key, status:"failed", error:"boom"} else {idempotency_key, status:"completed", artifact_id: ("LIN-" + .id), artifact_ref: ("linear://LIN-" + .id)} end))}'
SH
chmod +x "$partial_provider"
failed_provider="$tmp_dir/failed-provider.sh"
cat > "$failed_provider" <<'SH'
#!/usr/bin/env bash
jq '{status:"failed", artifacts:(.artifacts | map(if .id == "SMOKE_FEATURE_SCOREBOARD" then {idempotency_key, status:"failed", error:"boom"} else {idempotency_key, status:"completed", artifact_id: ("LIN-" + .id), artifact_ref: ("linear://LIN-" + .id)} end))}'
SH
chmod +x "$failed_provider"
assert "emit-work-items dry-run preserves ADLC task contracts" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --dry-run --json | jq -e '.dry_run == true and (.artifacts | length) >= 2 and all(.artifacts[]; (.artifact_type | length) > 0 and (.decision_contract | type) == \"object\" and (.verification_spec | type) == \"object\" and (.idempotency_key | contains(\":linear:\")))' >/dev/null"
assert "emit-work-items dry-run readiness report is ready" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --dry-run --json | jq -e '.readiness_report.status == \"ready\" and .readiness_report.totals.tasks >= 3' >/dev/null"
assert "emit-work-items preserves work_item_metadata in normalized artifacts" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --dry-run --json | jq -e 'any(.artifacts[]; .area == \"backend\" and .phase_label == \"coding\" and .target_project == \"smoke\" and (.labels | index(\"smoke\")) >= 0 and (.external_refs | index(\"EXT-1\")) >= 0)' >/dev/null"
jq '(.sections."8_task_tickets"[0].work_item_metadata.loop_contract_path) = "tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json" | (.sections."8_task_tickets"[0].work_item_metadata.loop_action_path) = "tests/fixtures/loop_maturity/valid-loop-action.json" | (.sections."8_task_tickets"[0].work_item_metadata.loop_maturity_report_path) = "tests/fixtures/loop_maturity/assisted-loop-report.json"' "$ROOT/docs/build-briefs/xia-adlc-remediation.json" > "$tmp_dir/loop-ref-brief.json"
assert "emit-work-items preserves loop contract refs" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/loop-ref-brief.json' --dry-run --json | jq -e '.artifacts[0].loop_contract_path == \"tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json\" and .artifacts[0].loop_action_path == \"tests/fixtures/loop_maturity/valid-loop-action.json\" and .artifacts[0].loop_maturity_report_path == \"tests/fixtures/loop_maturity/assisted-loop-report.json\"' >/dev/null"
jq '(.sections."8_task_tickets"[0].implementation_interface_contract) = {"id":"iface:cli-smoke","reuse":["scripts/adlc.py normalized_work_item_payload"],"consumes":["Build Brief task"],"emits":["normalized artifact"],"minimum_fields":[{"name":"task_id","kind":"string","constraint":"stable"}],"invariants":["optional fields remain optional"],"integration_points":["bin/adlc emit-work-items"],"validation_gates":["tests/test_adlc_cli.sh"]} | (.sections."8_task_tickets"[0].productionization_gate) = {"id":"prod:cli-smoke","claim":"CLI dry-run payload is production ready for local normalization.","coverage_state":"production_ready","operational_readiness":{"owner":"ADLC","rollback_path":"Revert the patch.","runbook_refs":["docs/specs/emitter-contract.md"]},"security_privacy":{"redaction_posture":"No secrets emitted."},"reliability_failure_modes":["Schema mismatch blocks mutation."],"validation_evidence":["tests/test_adlc_cli.sh"],"no_overclaim":["Does not prove external provider mutation."]}' "$ROOT/docs/build-briefs/xia-adlc-remediation.json" > "$tmp_dir/interface-prod-brief.json"
assert "emit-work-items preserves implementation interface and productionization contracts" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/interface-prod-brief.json' --dry-run --require-ready --json | jq -e '.readiness_report.status == \"ready\" and .artifacts[0].implementation_interface_contract.id == \"iface:cli-smoke\" and .artifacts[0].productionization_gate.coverage_state == \"production_ready\" and .artifacts[0].productionization_gate.no_overclaim[0] == \"Does not prove external provider mutation.\"' >/dev/null"
jq '(.sections."8_task_tickets"[0].productionization_gate) = {"id":"prod:overclaim","claim":"Task is production ready without evidence.","coverage_state":"production_ready","operational_readiness":{"owner":"ADLC","rollback_path":"Revert the patch.","runbook_refs":["docs/specs/emitter-contract.md"]},"security_privacy":{"redaction_posture":"No secrets emitted."},"reliability_failure_modes":[],"validation_evidence":[],"no_overclaim":[]}' "$ROOT/docs/build-briefs/xia-adlc-remediation.json" > "$tmp_dir/overclaimed-prod-brief.json"
assert "emit-work-items require-ready blocks overclaimed production_ready" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/overclaimed-prod-brief.json' --dry-run --json >'$tmp_dir/overclaimed-prod-result.json' && jq -e '.readiness_report.status == \"blocked\" and any(.readiness_report.issues[]; .rule == \"overclaimed_production_ready\")' '$tmp_dir/overclaimed-prod-result.json' >/dev/null && if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/overclaimed-prod-brief.json' --dry-run --require-ready --json >/dev/null 2>&1; then false; else true; fi"
printf '%s\n' '{"coding":"smoke"}' > "$tmp_dir/phase-project-map.json"
assert "emit-work-items phase-project map accepts matching metadata" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --dry-run --require-ready --phase-project-map '$tmp_dir/phase-project-map.json' --json | jq -e '.readiness_report.status == \"ready\"' >/dev/null"
assert "emit-work-items phase-project map blocks mismatched metadata" "if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --dry-run --require-ready --phase-project-map '{\"coding\":\"not-smoke\"}' --json >'$tmp_dir/invalid-phase-map.json' 2>/dev/null; then false; else true; fi"
jq '.enterprise_readiness_contract.validation_tasks = ["SMOKE_BUGFIX_AVERAGE"]' "$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json" > "$tmp_dir/invalid-brief.json"
assert "emit-work-items --require-ready fails on invalid validation task reference" "if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/invalid-brief.json' --dry-run --require-ready --json >'$tmp_dir/invalid-ready.json' 2>/dev/null; then false; else true; fi"
jq '.sections."8_task_tickets"[1].dependencies = ["GOV-ALIAS"]' "$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json" > "$tmp_dir/alias-brief.json"
guard_provider="$tmp_dir/guard-provider.sh"
cat > "$guard_provider" <<SH
#!/usr/bin/env bash
touch "$tmp_dir/provider-called"
printf '{"status":"completed"}\n'
SH
chmod +x "$guard_provider"
assert "emit-work-items readiness blocks unresolved aliases before provider mutation" "if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/alias-brief.json' --workspace '$tmp_dir/emitter' --allow-mutation --provider-command '$guard_provider' --require-ready --json >'$tmp_dir/alias-result.json' 2>/dev/null; then false; else [ ! -f '$tmp_dir/provider-called' ]; fi"
mkdir -p "$tmp_dir/external-state/.adlc"
cat > "$tmp_dir/external-state/.adlc/workflow_state.json" <<'JSON'
{"brief_id":"SMOKE-BRIEF-FEATURE-BUGFIX","session_id":"adlc-test","phase":"pr_prep","status":"planned","step":"ready","started_at":"2026-01-01T00:00:00Z","updated_at":"2026-01-01T00:00:00Z","resume_count":0,"checkpoint":{"workspace":"/tmp","history":[]},"side_effects":[{"idempotency_key":"SMOKE-BRIEF-FEATURE-BUGFIX:linear:EXT-DONE:upsert","tool_name":"linear-work-item-emitter","operation":"upsert_artifact","status":"completed","artifact_id":"EXT-DONE","artifact_ref":"linear://EXT-DONE","timestamp":"2026-01-01T00:00:00Z"}]}
JSON
jq '.sections."8_task_tickets"[1].dependencies = ["EXT-DONE"]' "$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json" > "$tmp_dir/external-dep-brief.json"
assert "emit-work-items resolves dependencies to terminal emitted artifact ids" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/external-dep-brief.json' --workspace '$tmp_dir/external-state' --dry-run --require-ready --json | jq -e '.readiness_report.status == \"ready\" and any(.dependency_links[]; .from == \"EXT-DONE\" and .to == \"SMOKE_FEATURE_SCOREBOARD\" and .type == \"blocks\")' >/dev/null"
mkdir -p "$tmp_dir/unrelated-state/.adlc"
cat > "$tmp_dir/unrelated-state/.adlc/workflow_state.json" <<'JSON'
{"brief_id":"SMOKE-BRIEF-FEATURE-BUGFIX","session_id":"adlc-test","phase":"pr_prep","status":"planned","step":"ready","started_at":"2026-01-01T00:00:00Z","updated_at":"2026-01-01T00:00:00Z","resume_count":0,"checkpoint":{"workspace":"/tmp","history":[]},"side_effects":[{"idempotency_key":"OTHER-BRIEF:linear:THING:upsert","tool_name":"linear-work-item-emitter","operation":"upsert_artifact","status":"completed","artifact_id":"WRONG_BRIEF","artifact_ref":"linear://WRONG_BRIEF","timestamp":"2026-01-01T00:00:00Z"},{"idempotency_key":"SMOKE-BRIEF-FEATURE-BUGFIX:linear:THING:upsert","tool_name":"github-work-item-emitter","operation":"upsert_artifact","status":"completed","artifact_id":"WRONG_TOOL","artifact_ref":"linear://WRONG_TOOL","timestamp":"2026-01-01T00:00:00Z"},{"idempotency_key":"SMOKE-BRIEF-FEATURE-BUGFIX:linear:THING:upsert","tool_name":"linear-work-item-emitter","operation":"delete_artifact","status":"completed","artifact_id":"WRONG_OP","artifact_ref":"linear://WRONG_OP","timestamp":"2026-01-01T00:00:00Z"}]}
JSON
assert "emit-work-items ignores unrelated terminal side effects for dependency readiness" "for alias in WRONG_BRIEF WRONG_TOOL WRONG_OP; do jq --arg alias \"\$alias\" '.sections.\"8_task_tickets\"[1].dependencies = [\$alias]' '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' > '$tmp_dir/unrelated-dep.json'; if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/unrelated-dep.json' --workspace '$tmp_dir/unrelated-state' --dry-run --require-ready --json >'$tmp_dir/unrelated-result.json' 2>/dev/null; then exit 1; fi; done"
assert "XIA remediation decomposition emits ready Linear work items" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/docs/build-briefs/xia-adlc-remediation.json' --dry-run --require-ready --phase-project-map '{\"phase:m2\":\"M2: Hosted Foundation\",\"phase:m4\":\"M4: Policy Graduation\"}' --json | jq -e '.readiness_report.status == \"ready\" and (.artifacts | length) == 6' >/dev/null"
assert "emit-work-items preserves decision gates and validation tasks as first-class artifacts" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/docs/build-briefs/xia-adlc-remediation.json' --dry-run --require-ready --phase-project-map '{\"phase:m2\":\"M2: Hosted Foundation\",\"phase:m4\":\"M4: Policy Graduation\"}' --json | jq -e '. as \$root | any(.artifacts[]; .id == \"XIA-DEC-BLOCK\" and .artifact_type == \"decision_gate\" and .blocks_implementation == true and .decision_contract.status == \"unresolved\") and any(.dependency_links[]; .from == \"XIA-DEC-BLOCK\" and .to == \"XIA-ADLC-READY\" and .type == \"blocks\") and (.enterprise_readiness_contract.validation_tasks as \$tasks | all(\$tasks[]; . as \$id | any(\$root.artifacts[]; .id == \$id and .artifact_type == \"validation_task\" and .executable == true)))' >/dev/null"
assert "emit-work-items mutation uses provider hook and records side effects" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --workspace '$tmp_dir/emitter' --allow-mutation --provider-command '$provider' --json | jq -e '.dry_run == false and .provider_result.artifact_count == (.artifacts | length) and (.state.side_effects | length) >= (.artifacts | length)' >/dev/null"
assert "emit-work-items mutation records provider-returned target metadata" "jq -e 'any(.side_effects[]; .idempotency_key == \"SMOKE-BRIEF-FEATURE-BUGFIX:linear:SMOKE_BUGFIX_AVERAGE:upsert\" and .artifact_id == \"LIN-SMOKE_BUGFIX_AVERAGE\" and .artifact_ref == \"linear://LIN-SMOKE_BUGFIX_AVERAGE\")' '$tmp_dir/emitter/.adlc/workflow_state.json' >/dev/null"
jq '.sections."8_task_tickets"[1].dependencies = ["LIN-SMOKE_BUGFIX_AVERAGE"]' "$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json" > "$tmp_dir/provider-dep-brief.json"
assert "emit-work-items resolves dependencies to provider-returned target artifact ids" "'$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$tmp_dir/provider-dep-brief.json' --workspace '$tmp_dir/emitter' --dry-run --require-ready --json | jq -e '.readiness_report.status == \"ready\" and any(.dependency_links[]; .from == \"LIN-SMOKE_BUGFIX_AVERAGE\" and .to == \"SMOKE_FEATURE_SCOREBOARD\" and .type == \"blocks\")' >/dev/null"
assert "emit-work-items surfaces per-artifact provider failures" "if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --workspace '$tmp_dir/partial-emitter' --allow-mutation --provider-command '$partial_provider' --json >'$tmp_dir/partial-result.json' 2>/dev/null; then false; else jq -e '.provider_result.status == \"failed\" and .provider_result.stop_reason == \"external_mutation_partial\" and any(.state.side_effects[]; .idempotency_key == \"SMOKE-BRIEF-FEATURE-BUGFIX:linear:SMOKE_FEATURE_SCOREBOARD:upsert\" and .status == \"failed\")' '$tmp_dir/partial-result.json' >/dev/null; fi"
assert "emit-work-items preserves partial stop reason on failed provider batches" "if '$ROOT/bin/adlc' emit-work-items --target linear --build-brief '$ROOT/tests/smoke/fixtures/feature_bugfix/.adlc/build_brief.json' --workspace '$tmp_dir/failed-emitter' --allow-mutation --provider-command '$failed_provider' --json >'$tmp_dir/failed-result.json' 2>/dev/null; then false; else jq -e '.provider_result.status == \"failed\" and .provider_result.stop_reason == \"external_mutation_partial\" and any(.state.side_effects[]; .idempotency_key == \"SMOKE-BRIEF-FEATURE-BUGFIX:linear:SMOKE_FEATURE_SCOREBOARD:upsert\" and .status == \"failed\")' '$tmp_dir/failed-result.json' >/dev/null; fi"

echo ""
echo "--- MCP Wrapper ---"
assert "mcp-tools emits MCP tool declarations" "'$ROOT/bin/adlc' mcp-tools --json | jq -e '(.tools | length) >= 12 and any(.tools[]; .name == \"adlc_validate_artifact\" and (.inputSchema.required | index(\"schema\"))) and any(.tools[]; .name == \"adlc_health_check\") and any(.tools[]; .name == \"adlc_run_phase\") and any(.tools[]; .name == \"adlc_emit_work_items\") and any(.tools[]; .name == \"adlc_compound_context\") and any(.tools[]; .name == \"adlc_loop_test_selection\" and .inputSchema.properties.require_test_results.type == \"boolean\") and any(.tools[]; .name == \"adlc_loop_budget_check\" and (.inputSchema.required | index(\"token_budget\")) and .inputSchema.properties.estimated_input_tokens.type == \"integer\") and any(.tools[]; .name == \"adlc_loop_action_validate\" and .inputSchema.properties.token_budget.type == \"string\") and any(.tools[]; .name == \"adlc_loop_maturity_audit\" and .inputSchema.properties.test_results.type == \"string\" and .inputSchema.properties.token_budget.type == \"string\" and (.inputSchema.properties | has(\"build_brief\") | not))' >/dev/null"
assert "mcp-serve handles initialize and tools/list" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2025-06-18\",\"capabilities\":{},\"clientInfo\":{\"name\":\"test\",\"version\":\"0\"}}}' '{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\"}' | '$ROOT/bin/adlc' mcp-serve | jq -s -e '.[0].result.capabilities.tools.listChanged == false and any(.[1].result.tools[]; .name == \"adlc_list_agents\")' >/dev/null"
assert "mcp-serve calls adlc_list_agents" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_list_agents\",\"arguments\":{}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.count >= 11' >/dev/null"
assert "mcp-serve calls health check" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":4,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_health_check\",\"arguments\":{}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"pass\"' >/dev/null"
assert "mcp-serve calls strict loop test selection" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_test_selection\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json\",\"test_plan\":\"tests/fixtures/loop_maturity/test-plan-complete-required.json\",\"test_results\":\"tests/fixtures/loop_maturity/test-results-complete-required.json\",\"require_test_results\":true}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"pass\" and (.result.structuredContent.executed_required_tests | index(\"required:test-selection\")) != null' >/dev/null"
assert "mcp-serve calls loop budget check" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_budget_check\",\"arguments\":{\"token_budget\":\"tests/fixtures/loop_maturity/token-budget-healthy.json\",\"estimated_input_tokens\":10,\"expected_output_tokens\":10,\"phase\":\"phase_5_codegen_context\",\"skill\":\"codegen-context\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"proceed\" and .result.structuredContent.budget_status.status == \"healthy\"' >/dev/null"
assert "mcp-serve calls loop action validation" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_action_validate\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json\",\"action\":\"tests/fixtures/loop_maturity/valid-loop-action.json\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-control-progress.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"admitted\"' >/dev/null"
assert "mcp-serve calls budgeted loop action validation" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_action_validate\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/budgeted-loop-contract.json\",\"action\":\"tests/fixtures/loop_maturity/budgeted-loop-action.json\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-budget-progress.json\",\"token_budget\":\"tests/fixtures/loop_maturity/token-budget-healthy.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"admitted\" and .result.structuredContent.budget_status.status == \"healthy\"' >/dev/null"
assert "mcp-serve resolves contract budget guard ref for action validation" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_action_validate\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/budgeted-loop-contract.json\",\"action\":\"tests/fixtures/loop_maturity/budgeted-loop-action.json\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-budget-progress.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.status == \"admitted\" and .result.structuredContent.budget_status.token_budget_ref == \"tests/fixtures/loop_maturity/token-budget-healthy.json\"' >/dev/null"
assert "mcp-serve calls loop maturity audit" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_maturity_audit\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/adlc-assisted-loop-contract.json\",\"workflow\":\"WORKFLOW.dot\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-control-progress.json\",\"test_plan\":\"tests/fixtures/loop_maturity/test-plan-complete-required.json\",\"test_results\":\"tests/fixtures/loop_maturity/test-results-complete-required.json\",\"action\":\"tests/fixtures/loop_maturity/valid-loop-action.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.maturity_verdict == \"assisted_loop\" and .result.structuredContent.dimension_scores.test_selection_cannot_be_gamed.score == 3' >/dev/null"
assert "mcp-serve calls budgeted loop maturity audit" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_maturity_audit\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/budgeted-loop-contract.json\",\"workflow\":\"WORKFLOW.dot\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-budget-progress.json\",\"test_plan\":\"tests/fixtures/loop_maturity/test-plan-complete-required.json\",\"test_results\":\"tests/fixtures/loop_maturity/test-results-complete-required.json\",\"action\":\"tests/fixtures/loop_maturity/budgeted-loop-action.json\",\"token_budget\":\"tests/fixtures/loop_maturity/token-budget-healthy.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.maturity_verdict == \"assisted_loop\" and .result.structuredContent.budget_status.status == \"healthy\"' >/dev/null"
assert "mcp-serve resolves contract budget guard ref for maturity audit" "printf '%s\n' '{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"tools/call\",\"params\":{\"name\":\"adlc_loop_maturity_audit\",\"arguments\":{\"loop_contract\":\"tests/fixtures/loop_maturity/budgeted-loop-contract.json\",\"workflow\":\"WORKFLOW.dot\",\"state\":\"tests/fixtures/loop_maturity/workflow-state-budget-progress.json\",\"test_plan\":\"tests/fixtures/loop_maturity/test-plan-complete-required.json\",\"test_results\":\"tests/fixtures/loop_maturity/test-results-complete-required.json\",\"action\":\"tests/fixtures/loop_maturity/budgeted-loop-action.json\"}}}' | '$ROOT/bin/adlc' mcp-serve | jq -e '.result.isError == false and .result.structuredContent.maturity_verdict == \"assisted_loop\" and .result.structuredContent.budget_status.token_budget_ref == \"tests/fixtures/loop_maturity/token-budget-healthy.json\"' >/dev/null"

echo ""
printf 'Results: %b%s passed%b, %b%s failed%b, %s total\n' "$GREEN" "$PASS" "$NC" "$RED" "$FAIL" "$NC" "$TOTAL"

if [ "$FAIL" -ne 0 ]; then
  exit 1
fi
