#!/usr/bin/env python3
"""Render public provider claims from conformance evidence."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/evidence/provider-conformance/support-matrix.json"
README = ROOT / "README.md"
DOC = ROOT / "docs/trust/support-matrix.md"
BEGIN = "<!-- BEGIN GENERATED SUPPORT MATRIX -->"
END = "<!-- END GENERATED SUPPORT MATRIX -->"


def release_ref() -> str:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    project = pyproject.split("[project]", 1)[1].split("[", 1)[0]
    match = re.search(r'^version\s*=\s*"([^"]+)"', project, re.MULTILINE)
    if not match:
        raise ValueError("pyproject project.version is missing")
    return f"v{match.group(1)}"


def display_provider(value: str) -> str:
    return {"codex": "Codex", "claude": "Claude Code"}.get(value, value.title())


def current_rows(data: dict) -> tuple[dict, dict]:
    active = data.get("configurations", [])
    if len(active) != 1:
        raise ValueError("public matrix requires exactly one current evidenced configuration")
    blocked = [row for row in data.get("excluded", []) if row.get("reason") == "credentials_missing"]
    if len(blocked) != 1:
        raise ValueError("public matrix requires exactly one credential-blocked evidence row")
    return active[0], blocked[0]


def readme_block(active: dict, blocked: dict) -> str:
    dimensions = active["dimensions"]
    if set(dimensions.values()) != {"pass"}:
        raise ValueError("labeled current row contains a non-passing dimension")
    return "\n".join(
        [
            BEGIN,
            "| Provider | Provider version | Harness | Loop | Label | Dimensions | Runs | Evidence commit |",
            "|---|---:|---|---|---|---|---:|---|",
            (
                f"| {display_provider(active['provider'])} | {active['provider_version']} | {active['harness']} | "
                f"{active['loop'].title()} | {active['label']} | installation, invocation, behavior, end-to-end: pass | "
                f"{active['run_count']} | `{active['source_commit'][:12]}` |"
            ),
            (
                f"| {display_provider(blocked['provider'])} | {blocked['provider_version']} | {blocked['harness']} | "
                f"{blocked['loop'].title()} | — | invocation: blocked (`{blocked['reason']}`); remaining dimensions: not run | "
                f"{blocked['run_count']} failed preflight | `{blocked['source_commit'][:12]}` |"
            ),
            END,
        ]
    )


def evidence_links(row: dict, source_ref: str) -> str:
    refs = row.get("evidence_refs", []) + row.get("canonical_ci_evidence_refs", [])
    rendered = []
    for ref in refs:
        name = Path(ref).name
        rendered.append(
            f"[`{name}`](https://github.com/bigeasyfreeman/adlc/blob/{source_ref}/docs/evidence/provider-conformance/{name})"
        )
    return ", ".join(rendered)


def docs_page(data: dict, active: dict, blocked: dict, source_ref: str) -> str:
    a = active["dimensions"]
    b = blocked["dimensions"]
    return f"""<!-- Generated by scripts/render_support_matrix.py from docs/evidence/provider-conformance/support-matrix.json. Do not edit by hand. -->
# Provider support matrix

Evidence generated from `docs/evidence/provider-conformance/support-matrix.json`.

| Provider | Provider version | Model | Harness | Loop | Label | Installation | Invocation | Behavior | End to end | Runs | Failed runs | Source commit |
|---|---:|---|---|---|---|---|---|---|---|---:|---:|---|
| {display_provider(active['provider'])} | {active['provider_version']} | {active['model']} | {active['harness']} | {active['loop'].title()} | {active['label']} | {a['installation']} | {a['invocation']} | {a['behavior']} | {a['end_to_end']} | {active['run_count']} | {active['failed_runs']} | `{active['source_commit'][:12]}` |
| {display_provider(blocked['provider'])} | {blocked['provider_version']} | {blocked['model']} | {blocked['harness']} | {blocked['loop'].title()} | — | {b['installation'].replace('_', ' ')} | {b['invocation']} | {b['behavior'].replace('_', ' ')} | {b['end_to_end'].replace('_', ' ')} | {blocked['run_count']} | {blocked['failed_runs']} | `{blocked['source_commit'][:12]}` |

## Evidence

- {display_provider(active['provider'])} beta row: {evidence_links(active, source_ref)}.
- {display_provider(blocked['provider'])} credential-blocked row: {evidence_links(blocked, source_ref)}.

Labels apply only to the named provider, harness, model, version, source commit, fixture, evidence, loop, and dimensions. The dash is not a support label; it means no label was earned because invocation was credential-blocked. Superseded, failed, and deterministic-only runs remain in the source evidence and do not upgrade the current row.

`doc_honesty_section`: This matrix reports repository evidence, including failures and exclusions.

`no_overclaim`: {data['no_overclaim']} A recorded pass does not guarantee future provider/model behavior or another loop.

`limitations`: {' '.join(data['limitations'])} Released-artifact support remains unproved.
"""


def replace_block(text: str, block: str) -> str:
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("README generated support markers must appear exactly once")
    prefix, remainder = text.split(BEGIN, 1)
    _, suffix = remainder.split(END, 1)
    return prefix + block + suffix


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail instead of writing when generated claims drift")
    args = parser.parse_args()

    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    active, blocked = current_rows(data)
    expected_readme = replace_block(README.read_text(encoding="utf-8"), readme_block(active, blocked))
    expected_doc = docs_page(data, active, blocked, release_ref())

    drift = []
    if README.read_text(encoding="utf-8") != expected_readme:
        drift.append("README.md generated support block")
    if not DOC.exists() or DOC.read_text(encoding="utf-8") != expected_doc:
        drift.append("docs/trust/support-matrix.md")

    if args.check:
        if drift:
            print("support claim drift: " + ", ".join(drift), file=sys.stderr)
            return 1
        print(f"support matrix: pass (source rows={data['source_report_count']})")
        return 0

    README.write_text(expected_readme, encoding="utf-8")
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(expected_doc, encoding="utf-8")
    print(f"rendered support claims from {SOURCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
